# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-InstallShield
version:      0.2
version_from: lib/Win32/InstallShield.pm
installdirs:  site
requires:
    XML::Parser:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
license: perl
