--- #YAML:1.0
name:                Win32-InstallShield
version:             0.4
abstract:            InstallShield data file interface
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    XML::Parser:                   2.34
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - Kirk Baucom <kbaucom@schizoid.com>
