--- #YAML:1.0
name:               Win32-InstallShield
version:            0.6
abstract:           InstallShield data file interface
author:
    - Kirk Baucom <kbaucom@schizoid.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    XML::Parser:  2.34
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
